name: Snake Game

on:
  schedule:
    # Atualiza a cada 5 horas
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Gera os arquivos da cobrinha
      - uses: Platane/snk@v3
        with:
          github_user_name: Vithor-jr
          outputs: dist/snake.svg

      - name: Commit e push das mudanças
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica na branch output (para usar no README)
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
